'use client';
import { FormEvent,useEffect,useMemo,useState } from 'react';
import { useParams } from 'next/navigation';
import { getSupabaseBrowser } from '@/lib/supabaseBrowser';
import { createEntryReceiptPdf } from '@/lib/sdda/entryReceiptPdf';
type Day={id:string;day_number:number;trial_date:string}; type Offer={id:string;trial_day_id:string;level:string;component:string;stream:string};
type Setup={name:string;host_club:string;venue?:string;payment_instructions?:string;cancellation_policy?:string;days:Day[];offerings:Offer[]};
const box='rounded-2xl border border-[#d9d8cf] bg-[#fffdf7] p-5 shadow-sm'; const field='w-full rounded-lg border border-[#bfc8c1] bg-white px-3 py-2';
const levelOrder=['Started','Advanced','Excellent','Elite'];
const runGroups=['Regular','Official','Second dog','FEO','BIS'] as const;
const empty={handler_name:'',handler_email:'',handler_phone:'',handler_address:'',participant_number:'',dog_call_name:'',dog_registered_name:'',dog_registration_number:'',registration_pending:false,breed:'',stream:'Amateur',formal_alerts:'',title_watch_note:'',reactivity:'None',waiver_accepted:false};
export default function Page(){const trialId=useParams<{trialId:string}>().trialId;const [setup,setSetup]=useState<Setup>();const [form,setForm]=useState(empty);const [chosen,setChosen]=useState<Set<string>>(new Set());const [runGroup,setRunGroup]=useState<Record<string,string>>({});const [step,setStep]=useState(1);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [receipt,setReceipt]=useState<{confirmation_code:string;receipt_token:string}|null>(null);
useEffect(()=>{void getSupabaseBrowser().rpc('sdda_public_trial_entry_setup',{target_trial_id:trialId}).then(({data,error})=>error?setError(error.message):setSetup(data as Setup));},[trialId]);
const offers=useMemo(()=>{const matching=setup?.offerings.filter(o=>o.stream===form.stream)||[];const elite=new Map<string,Offer>();(setup?.offerings||[]).filter(o=>o.level==='Elite').forEach(o=>{const key=`${o.trial_day_id}|${o.component}`;if(!elite.has(key)||o.stream===form.stream)elite.set(key,o)});return [...matching.filter(o=>o.level!=='Elite'),...elite.values()]},[setup,form.stream]);const set=(key:string,value:string|boolean)=>setForm(v=>({...v,[key]:value}));const toggle=(id:string)=>setChosen(v=>{const n=new Set(v);n.has(id)?n.delete(id):n.add(id);if(!n.has(id))setRunGroup(g=>{const copy={...g};delete copy[id];return copy});return n});
function advance(){setError('');if(step===1&&(!form.handler_name||!form.handler_email.includes('@')||!form.dog_call_name||!form.breed.trim()||(!form.registration_pending&&!form.dog_registration_number)))return setError('Complete the required competitor and dog information.');if(step===2&&!chosen.size)return setError('Select at least one offered component.');if(step===3&&!form.waiver_accepted)return setError('Accept the acknowledgement before reviewing.');setStep(s=>s+1);scrollTo(0,0)}
async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');const {data,error}=await getSupabaseBrowser().rpc('sdda_submit_public_entry',{target_trial_id:trialId,submission:{...form,runs:[...chosen].map(offering_id=>({offering_id,run_group:runGroup[offering_id]||'Regular'}))}});setBusy(false);if(error)return setError(error.message);const r=data as {confirmation_code:string;receipt_token:string};setReceipt(r);localStorage.setItem(`sdda-receipt-${r.confirmation_code}`,JSON.stringify({...r,trialId}));scrollTo(0,0)}
async function downloadReceipt(){if(!receipt||!setup)return;const selections=offers.filter(o=>chosen.has(o.id)).map(o=>`Day ${setup.days.find(d=>d.id===o.trial_day_id)?.day_number||'?'} - ${o.level} - ${o.component}${o.level==='Elite'?'':` - ${o.stream}`} - ${runGroup[o.id]||'Regular'}`);const bytes=await createEntryReceiptPdf({confirmationCode:receipt.confirmation_code,trialName:setup.name,handlerName:form.handler_name,dogName:form.dog_call_name,runCount:chosen.size,selections});const blob=new Blob([Uint8Array.from(bytes).buffer],{type:'application/pdf'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${receipt.confirmation_code}-entry-receipt.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
if(receipt)return <Shell title="Entry received" subtitle={setup?.name}><section className={box}><small className="font-bold uppercase">Confirmation number</small><p className="my-2 font-mono text-3xl font-bold text-[#225f45]">{receipt.confirmation_code}</p><div className="my-5 rounded-xl border border-[#d4b778] bg-[#fff5d8] p-4"><b>Received—not yet accepted.</b><p>The secretary must confirm your entry and payment instructions. Keep this receipt.</p></div><p>{form.handler_name} with {form.dog_call_name} · {chosen.size} component runs requested</p><div className="mt-5 flex flex-wrap gap-3 print:hidden"><button type="button" className="rounded-lg border border-[#225f45] bg-white px-5 py-3 font-bold text-[#225f45]" onClick={()=>window.print()}>Print receipt</button><button type="button" className="rounded-lg bg-[#225f45] px-5 py-3 font-bold text-white" onClick={()=>void downloadReceipt()}>Download receipt PDF</button></div></section></Shell>;
return <Shell title={setup?.name||'SDDA trial entry'} subtitle={setup&&`${setup.host_club}${setup.venue?` • ${setup.venue}`:''}`}><div className="mb-4 grid grid-cols-4 gap-2 text-center text-xs font-bold">{['Competitor & dog','Runs','Policies','Review'].map((x,i)=><div className={`rounded-lg p-3 ${step===i+1?'bg-[#b98935] text-white':'bg-white'}`} key={x}>{i+1}. {x}</div>)}</div>{error&&<div className="mb-4 rounded-xl border border-red-300 bg-red-50 p-4 text-red-800">{error}</div>}{!setup&&!error&&<section className={box}>Loading entry form…</section>}{setup&&<form onSubmit={submit}>
{step===1&&<div className="space-y-4"><Section title="Competitor information"><Grid><F label="Name *"><input className={field} value={form.handler_name} onChange={e=>set('handler_name',e.target.value)}/></F><F label="Email *"><input type="email" className={field} value={form.handler_email} onChange={e=>set('handler_email',e.target.value)}/></F><F label="Phone"><input className={field} value={form.handler_phone} onChange={e=>set('handler_phone',e.target.value)}/></F><F label="Registered participant number"><input className={field} value={form.participant_number} onChange={e=>set('participant_number',e.target.value)}/></F><F label="Mailing address"><textarea className={field} value={form.handler_address} onChange={e=>set('handler_address',e.target.value)}/></F></Grid></Section><Section title="Dog information"><Grid><F label="Dog call name *"><input className={field} value={form.dog_call_name} onChange={e=>set('dog_call_name',e.target.value)}/></F><F label="Registered name"><input className={field} value={form.dog_registered_name} onChange={e=>set('dog_registered_name',e.target.value)}/></F><F label="SDDA registration number *"><input disabled={form.registration_pending} className={field} value={form.dog_registration_number} onChange={e=>set('dog_registration_number',e.target.value)}/><label><input type="checkbox" checked={form.registration_pending} onChange={e=>set('registration_pending',e.target.checked)}/> Registration pending</label></F><F label="Breed (Mixed Breed put All Canadian) *"><input required className={field} value={form.breed} onChange={e=>set('breed',e.target.value)}/></F><F label="Stream (Instructors and Professionals must choose Working) *"><select className={field} value={form.stream} onChange={e=>{set('stream',e.target.value);setChosen(new Set())}}><option>Amateur</option><option>Working</option></select></F></Grid></Section></div>}
{step===2&&<Section title="Choose offered runs"><p className="mb-2">Amateur/Working applies to Started, Advanced and Excellent. Elite has no stream.</p><p className="mb-5 text-sm text-[#68736c]">For every selected run, tell the secretary whether it is Regular, Official/Volunteer, Second dog, FEO, or BIS. The secretary will confirm requests and capacity.</p>{setup.days.map(d=><div className="mb-6" key={d.id}><h3 className="border-b pb-2 font-serif text-2xl">Day {d.day_number} · {d.trial_date}</h3>{[...new Set(offers.filter(o=>o.trial_day_id===d.id).map(o=>o.level))].sort((a,b)=>levelOrder.indexOf(a)-levelOrder.indexOf(b)).map(level=><div className="mt-3" key={level}><b>{level}{level==='Elite'?' (no stream)':` - ${form.stream}`}</b><div className="mt-2 grid gap-2 sm:grid-cols-3">{offers.filter(o=>o.trial_day_id===d.id&&o.level===level).map(o=><div className="rounded-lg border bg-white p-3" key={o.id}><label className="flex items-center gap-3 font-semibold"><input type="checkbox" checked={chosen.has(o.id)} onChange={()=>toggle(o.id)}/>{o.component}</label>{chosen.has(o.id)&&<select aria-label={`${o.component} running-order request`} className={`${field} mt-3`} value={runGroup[o.id]||'Regular'} onChange={e=>setRunGroup(g=>({...g,[o.id]:e.target.value}))}>{runGroups.map(group=><option key={group}>{group}</option>)}</select>}</div>)}</div></div>)}</div>)}</Section>}
{step===3&&<div className="space-y-4"><Section title="Safety and title notes"><Grid><F label="Formal alert(s) — Started teams leave blank"><textarea className={field} value={form.formal_alerts} onChange={e=>set('formal_alerts',e.target.value)}/></F><F label="Championship title watch"><textarea className={field} value={form.title_watch_note} onChange={e=>set('title_watch_note',e.target.value)}/></F><F label="Is your dog reactive?"><select className={field} value={form.reactivity} onChange={e=>set('reactivity',e.target.value)}><option>None</option><option>Dogs</option><option>People</option><option>Both</option></select></F></Grid></Section><Section title="Payment and cancellation"><p className="whitespace-pre-wrap">{setup.payment_instructions||'Do not pay until the secretary confirms your entry and provides payment instructions.'}</p><p className="mt-3 whitespace-pre-wrap">{setup.cancellation_policy||'Entries are subject to the premium list cancellation policy.'}</p><label className="mt-5 flex gap-3 rounded-xl border border-[#d4b778] bg-[#fff5d8] p-4"><input type="checkbox" checked={form.waiver_accepted} onChange={e=>set('waiver_accepted',e.target.checked)}/>I reviewed my entry and agree to the payment and cancellation terms. *</label></Section></div>}
{step===4&&<Section title="Review before submitting"><p className="mb-4">You will receive a confirmation number immediately. Receipt does not mean secretary acceptance.</p><div className="rounded-xl bg-white p-4"><b>{form.handler_name}</b> · {form.handler_email}<br/><b>{form.dog_call_name}</b> · {form.dog_registration_number||'registration pending'}<br/>{chosen.size} component runs</div><div className="mt-4 space-y-2">{offers.filter(o=>chosen.has(o.id)).map(o=><div className="rounded-lg border bg-white p-3" key={o.id}>Day {setup.days.find(d=>d.id===o.trial_day_id)?.day_number} · {o.level} · {o.component}{o.level==='Elite'?'':` · ${o.stream}`} · <b>{runGroup[o.id]||'Regular'}</b></div>)}</div></Section>}
<div className="mt-4 flex justify-between">{step>1?<button type="button" className="rounded-lg border bg-white px-5 py-3 font-bold" onClick={()=>setStep(s=>s-1)}>Back</button>:<span/>}{step<4?<button type="button" className="rounded-lg bg-[#225f45] px-5 py-3 font-bold text-white" onClick={advance}>Continue</button>:<button disabled={busy} className="rounded-lg bg-[#225f45] px-5 py-3 font-bold text-white">{busy?'Submitting…':'Submit entry'}</button>}</div></form>}</Shell>}
function Shell({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <main className="min-h-screen bg-[#f3f0e8] p-4 text-[#18231d]"><div className="mx-auto max-w-4xl"><header className="rounded-t-3xl bg-[#225f45] p-7 text-white"><small className="font-bold uppercase tracking-[.18em]">SDDA TrialDesk</small><h1 className="font-serif text-4xl">{title}</h1>{subtitle&&<p>{subtitle}</p>}</header><div className="mt-4">{children}</div></div></main>};function Section({title,children}:{title:string;children:React.ReactNode}){return <section className={box}><h2 className="mb-4 font-serif text-3xl text-[#225f45]">{title}</h2>{children}</section>};function Grid({children}:{children:React.ReactNode}){return <div className="grid gap-4 md:grid-cols-2">{children}</div>};function F({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1 block font-bold">{label}</span>{children}</label>}
