'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import { Archive, CheckCircle2, Download, Loader2, LockKeyhole, RotateCcw, XCircle } from 'lucide-react';
import MainLayout from '@/components/layout/mainLayout';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { getSupabaseBrowser } from '@/lib/supabaseBrowser';
import { buildSddaTrialBackup, getSddaTrialWorkspace, listSddaEntries, listSddaGameScoringRuns, listSddaScoringRuns, setSddaTrialCompletion, type SddaTrialWorkspace } from '@/lib/sdda/trialRepository';
type Entry=Awaited<ReturnType<typeof listSddaEntries>>[number]; type ScentRun=Awaited<ReturnType<typeof listSddaScoringRuns>>[number]; type GameRun=Awaited<ReturnType<typeof listSddaGameScoringRuns>>[number];
function first<T>(value:T|T[]|null|undefined):T|null{return Array.isArray(value)?value[0]||null:value||null;} const safeName=(value:string)=>value.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'');
export default function TrialCloseoutPage(){
 const trialId=useParams<{trialId:string}>().trialId; const [trial,setTrial]=useState<SddaTrialWorkspace|null>(null); const [entries,setEntries]=useState<Entry[]>([]); const [scentRuns,setScentRuns]=useState<ScentRun[]>([]); const [gameRuns,setGameRuns]=useState<GameRun[]>([]); const [loading,setLoading]=useState(true); const [working,setWorking]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const client=getSupabaseBrowser();const [workspace,roster,scents,games]=await Promise.all([getSddaTrialWorkspace(client,trialId),listSddaEntries(client,trialId),listSddaScoringRuns(client,trialId),listSddaGameScoringRuns(client,trialId)]);setTrial(workspace);setEntries(roster);setScentRuns(scents);setGameRuns(games);}catch(caught){setError(caught instanceof Error?caught.message:'Unable to review trial closeout.');}finally{setLoading(false);}},[trialId]); useEffect(()=>{void load();},[load]);
 const review=useMemo(()=>{const accepted=entries.filter((entry)=>entry.confirmation_status==='accepted');const pending=entries.filter((entry)=>entry.confirmation_status==='received').length;const unscoredScent=scentRuns.filter((run)=>run.run_group!=='FEO'&&!first(run.sdda_scores)).length;const incompleteScent=scentRuns.filter((run)=>{const score=first(run.sdda_scores);return score&&(score.result==='qualifying'||score.result==='non_qualifying')&&(score.score==null||score.time_seconds==null);}).length;const unscoredGames=gameRuns.filter((run)=>run.entry_type!=='FEO'&&!first(run.sdda_game_scores)).length;const incompleteGames=gameRuns.filter((run)=>{const score=first(run.sdda_game_scores);return score&&(score.result==='pass'||score.result==='fail')&&score.time_seconds==null;}).length;const missingDayDetails=trial?.sdda_trial_days.filter((day)=>!day.sdda_trial_number?.trim()).length||0;const missingJudges=(trial?.sdda_trial_offerings.filter((offering)=>!offering.judge_name?.trim()&&!trial.sdda_trial_days.find((day)=>day.id===offering.trial_day_id)?.judge_name?.trim()).length||0)+(trial?.sdda_game_offerings.filter((offering)=>!offering.judge_name?.trim()&&!trial.sdda_trial_days.find((day)=>day.id===offering.trial_day_id)?.judge_name?.trim()).length||0);const blockers=[{label:'Accepted entries exist',ready:accepted.length>0,detail:accepted.length?`${accepted.length} entries accepted.`:'Accept at least one entry before completing the trial.'},{label:'Accepted Scent runs scored',ready:unscoredScent===0,detail:unscoredScent?`${unscoredScent} non-FEO run(s) are unscored.`:`${scentRuns.length} accepted Scent runs reviewed.`},{label:'Accepted Games runs scored',ready:unscoredGames===0,detail:unscoredGames?`${unscoredGames} non-FEO run(s) are unscored.`:`${gameRuns.length} accepted Games runs reviewed.`},{label:'Scores and times complete',ready:incompleteScent+incompleteGames===0,detail:incompleteScent+incompleteGames?`${incompleteScent+incompleteGames} scored run(s) are missing score/time details.`:'Recorded results include their required score/time details.'},{label:'Entry decisions complete',ready:pending===0,detail:pending?`${pending} received entries are still awaiting a decision.`:'Every received entry has a decision.'},{label:'Trial numbers assigned',ready:missingDayDetails===0,detail:missingDayDetails?`${missingDayDetails} trial day(s) are missing an SDDA trial number.`:'Every trial day has a trial number.'},{label:'Judges assigned',ready:missingJudges===0,detail:missingJudges?`${missingJudges} offering(s) have no component or day judge.`:'Every offering resolves to a judge.'}];const warnings=[{label:'Final exports reviewed',ready:false,detail:'Download and review results, official workbook, finances, activity journal, and the complete backup before locking.'}];return{blockers,warnings,canClose:blockers.every((item)=>item.ready)};},[entries,scentRuns,gameRuns,trial]);
 const backup=async()=>{if(!trial)return;setWorking(true);setError('');try{const data=await buildSddaTrialBackup(getSupabaseBrowser(),trialId);const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${safeName(trial.name)}-TrialDesk-backup-${new Date().toISOString().slice(0,10)}.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Complete trial backup downloaded. Keep it with the official closeout files.');}catch(caught){setError(caught instanceof Error?caught.message:'Unable to download the backup.');}finally{setWorking(false);}};
 const changeCompletion=async(complete:boolean)=>{if(complete&&!window.confirm('Complete this trial and lock operational editing? Download a backup first.'))return;if(!complete&&!window.confirm('Reopen this completed trial for corrections? This action is recorded.'))return;setWorking(true);setError('');try{await setSddaTrialCompletion(getSupabaseBrowser(),trialId,complete);setMessage(complete?'Trial completed and editing locked.':'Trial reopened in Entries Closed status.');await load();}catch(caught){setError(caught instanceof Error?caught.message:'Unable to change trial completion.');}finally{setWorking(false);}};
 return <MainLayout title="Trial closeout" breadcrumbItems={[{label:'Trials',href:'/dashboard/trials'},{label:trial?.name||'Trial',href:`/dashboard/trials/${trialId}`},{label:'Closeout'}]}><div className="mx-auto max-w-5xl space-y-5"><Card className="border-[#c8d7cd] bg-[#fffdf7]"><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 font-serif text-3xl text-[#225f45]"><Archive className="h-7 w-7"/>Trial closeout</CardTitle><CardDescription>Review operational completeness, download a durable backup, and lock the trial after final exports are checked.</CardDescription></div><Badge className={trial?.status==='completed'?'bg-green-700 text-white':'bg-[#b98935] text-white'}>{trial?.status.replaceAll('_',' ')||'Loading'}</Badge></div></CardHeader></Card>{error&&<Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}{message&&<Alert className="border-green-300 bg-green-50 text-green-900"><AlertDescription>{message}</AlertDescription></Alert>}{loading?<div className="flex justify-center p-12"><Loader2 className="h-8 w-8 animate-spin"/></div>:<><Checklist title="Required before completion" items={review.blockers}/><Checklist title="Review before final submission" items={review.warnings}/><Card><CardHeader><CardTitle>Final export package</CardTitle><CardDescription>Download these records before completing the trial.</CardDescription></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2"><ExportLink href={`/dashboard/trials/${trialId}/results`} label="Results & placements"/><ExportLink href={`/dashboard/trials/${trialId}/workbook`} label="Official SDDA workbook"/><ExportLink href={`/dashboard/trials/${trialId}/financials`} label="Financial statement"/><ExportLink href={`/dashboard/trials/${trialId}/activity`} label="Activity journal"/><Button variant="outline" className="sm:col-span-2" disabled={working} onClick={()=>void backup()}><Download className="mr-2 h-4 w-4"/>Download complete trial backup (JSON)</Button></CardContent></Card><Card className={trial?.status==='completed'?'border-green-400 bg-green-50':'border-[#d9d8cf]'}><CardHeader><CardTitle>{trial?.status==='completed'?'Trial is completed and locked':'Complete the trial'}</CardTitle><CardDescription>{trial?.status==='completed'?'Operational records cannot be changed until an authorized secretary reopens the trial.':'Completion locks entries, offerings, running orders, scores, and finances at the database.'}</CardDescription></CardHeader><CardContent>{trial?.status==='completed'?<Button variant="outline" disabled={working} onClick={()=>void changeCompletion(false)}><RotateCcw className="mr-2 h-4 w-4"/>Reopen for corrections</Button>:<Button disabled={working||!review.canClose} onClick={()=>void changeCompletion(true)}><LockKeyhole className="mr-2 h-4 w-4"/>Complete and lock trial</Button>}</CardContent></Card></>}</div></MainLayout>;
}
function Checklist({title,items}:{title:string;items:Array<{label:string;ready:boolean;detail:string}>}){return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-2">{items.map((item)=><div key={item.label} className={`flex gap-3 rounded-lg border p-3 ${item.ready?'border-green-200 bg-green-50':'border-amber-300 bg-amber-50'}`}>{item.ready?<CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-green-700"/>:<XCircle className="mt-0.5 h-5 w-5 shrink-0 text-amber-800"/>}<div><strong>{item.label}</strong><p className="text-sm text-[#68736c]">{item.detail}</p></div></div>)}</CardContent></Card>} function ExportLink({href,label}:{href:string;label:string}){return <a className="rounded-md border bg-white px-4 py-3 font-semibold text-[#225f45] hover:bg-[#f7f8f4]" href={href}>{label}</a>}
